version: '3.8'

services:
  postgres:
    build:
      context: ./database
    container_name: my_postgres_container
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./application
    container_name: my_backend_container
    depends_on:
      - postgres
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"

volumes:
  postgres_data:


