version: '3.8'

services:
  postgres:
    build:
      context: ./database
    container_name: my_postgres_container
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data


  backend:
    build: ./backend
    container_name: my_backend_container
    env_file:
      - .env
    depends_on:
      - postgres
    command: sh run.sh
    ports:
      - "8000:8000"
    volumes:
      - ./backend/transcendence/media:/app/transcendence/media

  frontend:
    build: ./frontend
    container_name: my_frontend_container
    command: npm run start
    ports:
      - "4242:4242"
    volumes:
      - ./nginx/ssl:/etc/ssl/certs

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: my_nginx_container
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf  # Nginx configuration
    ports:
      - "80:80"   # HTTP
      - "443:443" # HTTPS
    depends_on:
      - frontend
      - backend
    restart: on-failure

volumes:
  postgres_data:
