version: '3.8'

services:
  postgres:
    build:
      context: ./database
    container_name: my_postgres_container
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U myuser" ]
      interval: 10s
      retries: 5
      start_period: 30s

  backend:
    build: ./backend
    container_name: my_backend_container
    depends_on:
      - postgres
    command: sh run.sh
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    container_name: my_frontend_container
    command: npm run start
    ports:
      - "4242:4242"

volumes:
  postgres_data:


