version: '3.8'

services:
  postgres:
    build:
      context: ./database
    container_name: my_postgres_container
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - t_network


  backend:
    build: ./backend
    container_name: my_backend_container
    env_file:
      - .env
    depends_on:
      - postgres
      - nginx
    command: sh run.sh
    volumes:
      - ./backend/transcendence/media:/app/transcendence/media
    networks:
      - t_network

  frontend:
    build: ./frontend
    container_name: my_frontend_container
    command: npm run start
    volumes:
      - ./nginx/ssl:/etc/ssl/certs
    networks:
      - t_network

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: my_nginx_container
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf  # Nginx configuration
    ports:
      - "80:80"   # HTTP
      - "443:443" # HTTPS
    networks:
      - t_network
      - public_network
    restart: on-failure

volumes:
  postgres_data:


networks:
  t_network:
    internal: true
  public_network:
    driver: bridge