version: '3'

includes:
  frontend:
    taskfile: ./frontend/Taskfile.yml
    dir: ./frontend

tasks:
  frontend:
    cmds:
      - task: frontend:run

  kill-frontend:
    cmds:
      - task: frontend:kill

  start-dependencies:
    cmds:
      - task: stop-dependencies
      - docker compose up -d

  stop-dependencies:
    cmds:
      - docker compose down