version: '3'

includes:
  frontend:
    taskfile: ./frontend/Taskfile.yml
    dir: ./frontend

tasks:
  frontend:
    cmds:
      - task: frontend:run

  kill-frontend:
    cmds:
      - task: frontend:kill

  run:
    cmds:
      - task: stop-dependencies
      - docker compose up -d --build

  stop-dependencies:
    cmds:
      - docker compose down

  clean:
    cmds:
      - task: stop-dependencies
      - docker system prune -af
      - docker volume prune -af
  re:
    cmds:
      - task: clean
      - task: run