const BACKEND_PATH = 'https://' + 'localhost' +'/api';
const TokenRefreshEndpoint = BACKEND_PATH + '/token/refresh/';
const friendsEndpoint = BACKEND_PATH + '/friends/';
const userEndpoint = BACKEND_PATH + '/users/';
const PongEndpoint = BACKEND_PATH + '/pong/';
const TTTEndpoint = BACKEND_PATH + '/ttt/';
const loginEndpoint = BACKEND_PATH + '/login/';
const profileEndpoint = BACKEND_PATH + '/profile/';
const changeEmailEndpoint = BACKEND_PATH + '/profile/change-email';
const changeUsernameEndpoint = BACKEND_PATH + '/profile/username';
const signupEndpoint = BACKEND_PATH + '/signup/';
const graphEndpoint = BACKEND_PATH + '/graph/';
const tournamentEndpoint = BACKEND_PATH + '/tournament/'
